-- MySQL Script generated by MySQL Workbench
-- Wed Jun 26 21:22:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancopokemon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancopokemon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancopokemon` DEFAULT CHARACTER SET utf8 ;
USE `bancopokemon` ;

-- -----------------------------------------------------
-- Table `bancopokemon`.`tb_pokemon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancopokemon`.`tb_pokemon` ;

CREATE TABLE IF NOT EXISTS `bancopokemon`.`tb_pokemon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pokemon` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancopokemon`.`tb_pokemonEletrico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancopokemon`.`tb_pokemonEletrico` ;

CREATE TABLE IF NOT EXISTS `bancopokemon`.`tb_pokemonEletrico` (
  `id_pEletrico` INT NOT NULL,
  `pokemonEletrico` VARCHAR(45) NULL,
  `tipoE` VARCHAR(10) NULL,
  PRIMARY KEY (`id_pEletrico`),
  CONSTRAINT `pokemon_Eletrico_FK`
    FOREIGN KEY (`id_pEletrico`)
    REFERENCES `bancopokemon`.`tb_pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pokemonEletrico_UNIQUE` ON `bancopokemon`.`tb_pokemonEletrico` (`pokemonEletrico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bancopokemon`.`tb_pokemonFogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancopokemon`.`tb_pokemonFogo` ;

CREATE TABLE IF NOT EXISTS `bancopokemon`.`tb_pokemonFogo` (
  `id_pFogo` INT NOT NULL,
  `pokemonFogo` VARCHAR(45) NULL,
  `tipoF` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pFogo`),
  CONSTRAINT `pokemon_Fogo_FK`
    FOREIGN KEY (`id_pFogo`)
    REFERENCES `bancopokemon`.`tb_pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pokemonFogo_UNIQUE` ON `bancopokemon`.`tb_pokemonFogo` (`pokemonFogo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bancopokemon`.`tb_pokemonVoador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancopokemon`.`tb_pokemonVoador` ;

CREATE TABLE IF NOT EXISTS `bancopokemon`.`tb_pokemonVoador` (
  `id_pVoador` INT NOT NULL,
  `pokemonVoador` VARCHAR(45) NULL,
  `tipoV` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pVoador`),
  CONSTRAINT `pokemon_Voador_FK`
    FOREIGN KEY (`id_pVoador`)
    REFERENCES `bancopokemon`.`tb_pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `pokemonVoador_UNIQUE` ON `bancopokemon`.`tb_pokemonVoador` (`pokemonVoador` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bancopokemon`.`tb_pokemon_totalizador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancopokemon`.`tb_pokemon_totalizador` ;

CREATE TABLE IF NOT EXISTS `bancopokemon`.`tb_pokemon_totalizador` (
  `idtb_totalizador` INT NOT NULL,
  `total_eletrico` INT NULL,
  `total_fogo` INT NULL,
  `total_voador` INT NULL,
  `tb_pokemon_id` INT NOT NULL,
  PRIMARY KEY (`idtb_totalizador`),
  CONSTRAINT `fk_tb_pokemon_totalizador_tb_pokemon1`
    FOREIGN KEY (`tb_pokemon_id`)
    REFERENCES `bancopokemon`.`tb_pokemon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_pokemon_totalizador_tb_pokemon1_idx` ON `bancopokemon`.`tb_pokemon_totalizador` (`tb_pokemon_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bancopokemon`.`tb_pokemon_deletados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancopokemon`.`tb_pokemon_deletados` ;

CREATE TABLE IF NOT EXISTS `bancopokemon`.`tb_pokemon_deletados` (
  `id` VARCHAR(45) NOT NULL,
  `pokemon` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bancopokemon`.`tb_pokemon`
-- -----------------------------------------------------
START TRANSACTION;
USE `bancopokemon`;
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (1, 'pikachu', 'eletrico');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (2, 'miraidon', 'eletrico');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (3, 'charmander', 'fogo');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (4, 'fuecoco', 'fogo');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (5, 'miraidon', 'eletrico');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (6, 'pidgeotto', 'voador');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (7, 'butterfree', 'voador');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (8, 'butterfree', 'voador');
INSERT INTO `bancopokemon`.`tb_pokemon` (`id`, `pokemon`, `tipo`) VALUES (9, 'fuecoco', 'fogo');

COMMIT;

